version: '3'
services:
  statusserver:
    build: ./statusserver
    image: parisbutterfield/restswitch:statusserver2amd64

  authserver:
    build: ./authserver
    image: parisbutterfield/restswitch:authserver2amd64

  switchserver:
    build: ./switchserver
    image: parisbutterfield/restswitch:switchserver2amd64
